# Generated by Django 3.2.4 on 2021-06-25 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact_no', models.BigIntegerField()),
                ('Instagram_handle', models.CharField(blank=True, max_length=1000, null=True)),
                ('Date', models.DateField(default=datetime.date(2021, 6, 25))),
                ('Slot', models.TimeField()),
                ('Subject', models.CharField(choices=[('BRIDAL MAKEUP', 'BRIDAL MAKEUP'), ('SKIN CONSULTANCY', 'SKIN CONSULTANCY'), ('PARTY MAKEUP', 'PARTY MAKEUP'), ('SELF GROOMING', 'SELF GROOMING'), ('PROFESSIONAL MAKEUP COURSE', 'PROFESSIONAL MAKEUP CLASS'), ('EVENT MAKEUP', 'EVENT MAKEUP')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enquiry', models.CharField(max_length=1000)),
            ],
        ),
    ]
