# Generated by Django 3.2.4 on 2021-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studiosite', '0002_auto_20210625_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact_no', models.BigIntegerField()),
                ('Instagram_handle', models.CharField(blank=True, max_length=1000, null=True)),
                ('Makeup', models.CharField(choices=[('BRIDAL MAKEUP', 'BRIDAL MAKEUP'), ('SKIN CONSULTANCY', 'SKIN CONSULTANCY'), ('PARTY MAKEUP', 'PARTY MAKEUP'), ('SELF GROOMING', 'SELF GROOMING'), ('PROFESSIONAL MAKEUP COURSE', 'PROFESSIONAL MAKEUP CLASS'), ('EVENT MAKEUP', 'EVENT MAKEUP')], max_length=100)),
                ('Feedback', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
