# Generated by Django 3.2.4 on 2021-07-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studiosite', '0006_gallery_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='thumb',
        ),
    ]
